heat_template_version: 2013-05-23

description: >
  A HOT template that spins up an instance, attaches Cinder volume,
  installs Apache and configures security groups accordingly.

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the instance
    constraints:
      - custom_constraint: nova.keypair
        description: Must name a public key (pair) known to Nova
  flavor:
    type: string
    description: Flavor for the instance to be created
    default: m1.small
    constraints:
      - custom_constraint: nova.flavor
        description: Must be a flavor known to Nova
  image:
    type: string
    description: >
      Name or ID of the image to use for the instance.
      You can get the default from
      http://cloud.fedoraproject.org/fedora-20.x86_64.qcow2
      There is also
      http://cloud.fedoraproject.org/fedora-20.i386.qcow2
      Any image should work since this template
      does not ask the VM to do anything.
    constraints:
      - custom_constraint: glance.image
        description: Must identify an image known to Glance
  network:
    type: string
    description: The network for the VM
    default: private
  vol_az:
    type: string
    description: The AZ to attach volume
    default: cinderAZ_1
  vol_size:
    type: number
    description: The size of the Cinder volume
    default: 1

resources:
  configuration:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash -v
        yum -y install httpd
        chkconfig --levels 235 httpd on
        service httpd start

  deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: {get_resource: configuration}
      server: {get_resource: app_instance}

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: web
      rules: [
        {
          remote_ip_prefix: 0.0.0.0/0,
          protocol: tcp,
          port_range_min: 22,
          port_range_max: 22
        },
        {
          remote_ip_prefix: 0.0.0.0/0,
          protocol: tcp,
          port_range_min: 80,
          port_range_max: 80,
        },
        {
          remote_ip_prefix: 0.0.0.0/0,
          protocol: tcp,
          port_range_min: 443,
          port_range_max: 443,
        },
      ]
  
  app_instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: [{network: {get_param: network} }]
      security_groups: [{ get_resource: security_group }]
      user_data_format: SOFTWARE_CONFIG
  
  my_vol:
    type: OS::Cinder::Volume
    properties:
      availability_zone: { get_param: vol_az }
      size: { get_param: vol_size }
      volume_type: lvm

  vol_att:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: app_instance }
      volume_id: { get_resource: my_vol }
      mountpoint: /dev/vdb

outputs:
  instance_networks:
    description: The IP addresses of the deployed instance
    value: { get_attr: [app_instance, networks] }
